project_id = "akstlpiqjvgbjjnawqfn"

[functions.enrich-lead]
verify_jwt = false

[functions.scrape-leads]
verify_jwt = false

[functions.extract-whatsapp]
verify_jwt = false

[functions.manage-evolution]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.ai-whatsapp-hook]
verify_jwt = false
